package output

import (
	"fmt"
	"strings"
	"time"
)

const (
	watermarkMessage = "This file was generated by the BoardingHub OpenAPI Code Generator. Do not edit directly."
)

func getWatermark(version, extn string) string {
	datetime := time.Now().Format("Mon Jan 2 2006 15:04:05 MST")

	switch extn {
	case ".ts":
		format := strings.TrimPrefix(`
/**
 * %s
 *
 * 	- version: %s
 * 	- timestamp: %s
 */

`, "\n")
		return fmt.Sprintf(format, watermarkMessage, version, datetime)
	default:
		return ""
	}
}
